### ISSUE TITLE
Не проходит тесты

### ISSUE THREAD

**Issue by VEAlekseev** [VEAlekseev/web-interface#1]
1.Запуск теста
```
open("http://localhost:9999");
SelenideElement form = $("[class=\"form form_size_m form_theme_alfa-on-white\"]");
form.$("[data-test-id=name] input").setValue("Иванов Иван");
form.$("[data-test-id=phone] input").setValue("+79111111111");
form.$("[data-test-id=agreement]").click();
form.$("[class=\"button button_view_extra button_size_m button_theme_alfa-on-white\"]").click();
$("data-test-id=\"order-success\"").shouldHave(exactText("  Ваша заявка успешно отправлена! Наш менеджер свяжется с вами в ближайшее время."));
```
2.Формы заполняются корректно
3.При сравнение надписи об отправке тест падает

Ожидалось что все поля заполняться и тест пройдется без проблем.
![image](https://user-images.githubusercontent.com/56976270/70854141-aba17880-1ec8-11ea-9542-61b9e199ca06.png)
![image](https://user-images.githubusercontent.com/56976270/70854151-c70c8380-1ec8-11ea-98f2-ffcbc4beb59a.png)

Я бы выделил ключевые моменты, но не понимаю что из этого ключевое
Окружение: Windows 10x64, java.version: '11.0.4' , https://github.com/VEAlekseev/web-interface

[reports.zip](https://github.com/VEAlekseev/web-interface/files/3964299/reports.zip)

**Comment by supremko** [comment]
Открываешь в браузере

`http://localhost:9999`

вводишь в консоли

`$$('[form="form-field form-field_size_m form-field_theme_alfa-on-white"]')`

Видишь что-то в итоге? Если нет, то и Selenide тоже не видит, соответственно не вставит туда ничего и не нажмет.

**Comment by VEAlekseev** [comment]
формы находятся внутри этого класса, но Selenide ничего не видит

![image](https://user-images.githubusercontent.com/56976270/70852861-60cb3500-1eb7-11ea-906b-aafa1b664c9b.png)

**Comment by VEAlekseev** [comment]
не проходит проверку все равно, видимо из-за галочки которая отображается кодом

` $("[data-test-id=.order-success]").shouldHave(exactText("\"  Ваша заявка успешно отправлена! Наш менеджер свяжется с вами в ближайшее время.\""));`


![image](https://user-images.githubusercontent.com/56976270/70853269-af2f0280-1ebc-11ea-8793-4e5aaa700472.png)

**Comment by supremko** [comment]
Зачем тебе лишние символы в exactText?
`exactText("Ваша заявка успешно отправлена! Наш менеджер свяжется с вами в ближайшее время.")`

**Comment by VEAlekseev** [comment]
потому что в html там пробелы, но я пробовал и с одним пробелом и бе3 тест все равно падает. Да и как вы написали тест падает.

**Comment by supremko** [comment]
Отправь текст последней ошибки.

**Comment by VEAlekseev** [comment]
![image](https://user-images.githubusercontent.com/56976270/70854141-aba17880-1ec8-11ea-9542-61b9e199ca06.png)
![image](https://user-images.githubusercontent.com/56976270/70854151-c70c8380-1ec8-11ea-98f2-ffcbc4beb59a.png)

**Comment by supremko** [comment]
![image](https://user-images.githubusercontent.com/505723/70861619-c6640380-1f41-11ea-8930-74e6068b7bda.png)
опять же синтаксис

**Comment by VEAlekseev** [comment]
методом научного тыка проблему решил.
